### ISSUE TITLE
Mermaid.js sets static height in SVG

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/respec-mermaid#2]
Mermaid.js seems to set a static height parameter in the SVG that conflicts with ReSpec layout. Namely, the height is 2x what it should be for wide diagrams. We might need to clean up the SVG source before inserting it in the document. We might also need to make sure we do this as a part of post-processing instead of pre-processing.

**Comment by jandrieu** [comment]
Looks like if we just get rid of the height attribute, it works in the DOM. Can we configure the processor to just avoid adding the height?

**Comment by msporny** [comment]
> Looks like if we just get rid of the height attribute, it works in the DOM. Can we configure the processor to just avoid adding the height?

Done, released in new v1.0.1 of respec-mermaid. Use the following code block to upgrade:

> <script class="remove" src="https://cdn.jsdelivr.net/gh/digitalbazaar/respec-mermaid@1.0.1/dist/main.js"></script>
