### ISSUE TITLE
Handling of \n

### ISSUE THREAD

**Issue by eric-schuh** [digitalbazaar/respec-mermaid#3]
I can probably handle this on my side but currently the converter Joe and I are writing to convert from our VP diagrams to Mermaid injects a \n to represent a new line. Not the biggest of deals but would be nice if the renderer understood \n as it currently prevents diagrams from being formed. I attached an example output from our converter for reference. (its a .json but had to change to .txt because github doesn't like .json)
[test.txt](https://github.com/digitalbazaar/respec-mermaid/files/8613767/test.txt)

**Comment by msporny** [comment]
I don't think mermaid supports newlines in their diagrams. I was surprised by this as well when I tried to use them. I couldn't figure out how to inject newlines into mermaid diagrams (which is something that's supported in plantuml, but not mermaid, it seems).
